# Generated by Django 5.1.1 on 2024-10-21 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('privilege_id', models.AutoField(primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevels',
            fields=[
                ('user_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_level', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userlevels')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevelPrivileges',
            fields=[
                ('user_level_privilege_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.privileges')),
                ('user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.userlevels')),
            ],
            options={
                'unique_together': {('user_level', 'privilege')},
            },
        ),
    ]
